#!/usr/bin/perl
# ii, Interest Integrator
# Ron Hale-Evans, rwhe@ludism.org
# 2010-05-20

$nargs = $#ARGV + 1;
srand;

# You may need to adjust the following values,
# depending on your environment
$home = $ENV{HOME};
$obsessions = "obsessions.txt";
$browser = "firefox";
#$browser = "google-chrome";

# Usage information
if ($nargs > 2)
{
    $two = "\"ii chimp hilarious-consequences\" googles both terms.";
    $one = "\"ii chimp\" googles \"chimp\" plus a random obsession.";
    $zero = "\"ii\" by itself googles two random obsessions.";
    die "usage:\n$two\n$one\n$zero\n";
}
elsif ($nargs == 2)
{
    $arg1 = $ARGV[0];
    $arg2 = $ARGV[1];
}
elsif ($nargs == 1)
{
    $arg1 = $ARGV[0];
    $arg2 = random_obsession();    
}
else 
{
    $arg1 = random_obsession();
    $arg2 = random_obsession();    
}

$arg1 = munge($arg1);
$arg2 = munge($arg2);

$url = "http://www.google.com/search?num=100&q=$arg1+$arg2";
print "$url\n";
`$browser '$url'`;

sub random_obsession()
{
    open FILE, "<$obsessions" or die "Could not open obsessions.txt: $!\n";
    rand($.) <1 and ($line=$_) while <FILE>;
    close FILE;
    return($line);
}

# Tweak the search terms so they can form part of a valid URL
sub munge($)
{
    my ($a) = @_;

    chomp($a);
    $a =~ s/\"/\%22/sgi;
    $a =~ s/\+/\%2B/sgi;
    $a =~ s/ /\+/sgi;

    return($a);
}
