#!/usr/bin/perl
# tjd, Truncated Julian Day calculator
# Ron Hale-Evans, rwhe@ludism.org

use Time::HiRes qw(gettimeofday);

$day = 24 * 60 * 60;

#$in_file = $ARGV[0];

while (true)
{
    # Clear screen
    system("clear");

    $curtime = `date +%s`;
    chomp($curtime);
    $unixday = $curtime / $day;
    $jd = $unixday + 2440587.5;

    $jdint = int ($jd);
    $jdfrac = $jd - $jdint;
    
    $tjdint = $jdint % 10000;
    $tjdfrac = $jdfrac - 0.5;

    $tjd = $tjdint + $tjdfrac;

    print "Unix time = $curtime\n";
    print "Unix day = $unixday\n";
    print "Julian day = $jd\n";
    printf "Stardate %04.2f (TJD)\n", $tjd;

    sleep 1;
}
